// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManejoInventario_AngularTS_.NET_CORE.Server.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20241019211222_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManejoInventario_AngularTS_.NET_CORE.Server.Models.Prioridad", b =>
                {
                    b.Property<int>("PrioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrioID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrioID");

                    b.ToTable("Prioridad");
                });

            modelBuilder.Entity("ManejoInventario_AngularTS_.NET_CORE.Server.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaCompleto")
                        .HasColumnType("bit");

                    b.Property<int>("PrioID")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrioID");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("ManejoInventario_AngularTS_.NET_CORE.Server.Models.Tarea", b =>
                {
                    b.HasOne("ManejoInventario_AngularTS_.NET_CORE.Server.Models.Prioridad", "Prioridad")
                        .WithMany()
                        .HasForeignKey("PrioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prioridad");
                });
#pragma warning restore 612, 618
        }
    }
}
